### ISSUE TITLE
[Feature Requestion] Add ZIP Code Support for CVS

### ISSUE THREAD

**Issue by kraj011** [RebootJeff/cowGoesMoo#30]
Hi!
Currently the CVS checker just looks at statewide availability instead of looking at specific zip codes. It would be nice to have it check based on zip code for more accurate alerts.

Thanks!

**Comment by RebootJeff** [comment]
The CVS website doesn't provide data broken down by zip code. Their website lets you look by state and then shows you CVS locations by city. Maybe CowGoesMoo can be configured to only pay attention to certain cities.

**Comment by kraj011** [comment]
Once you fill out the initial questionnaire, it allows you to input zip code and it'll show you the locations near that zip code with vaccine availability. However, it is very volatile as appointments get booked instantly. I agree then though that filtering by City in the initial page and checking availability should be the way to go 😄
